### ISSUE TITLE
undefined method alignment? for NilClass

### ISSUE THREAD

**Issue by Reppinger** [CoralineAda/fukuzatsu#5]
After running:
`fuku check src/my_file.rb`

I received: 

> C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:32:in `block in align_column': undefined method `alignment?' for nil:NilClass (NoMethodError)
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:30:in `each'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:30:in `each_with_index'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:30:in `align_column'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/lib/fukuzatsu/formatters/text.rb:36:in `export'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/lib/fukuzatsu/parser.rb:24:in `block in report'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/lib/fukuzatsu/parser.rb:23:in `each'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/lib/fukuzatsu/parser.rb:23:in `report'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/lib/fukuzatsu/cli.rb:22:in `check'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
>         from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/fukuzatsu-2.3.1/bin/fuku:3:in `<top (required)>'
>         from C:/Ruby24-x64/bin/fuku:23:in `load'
>         from C:/Ruby24-x64/bin/fuku:23:in `<main>'

**Comment by slieker-d** [comment]
Same problem here. Is this library still supported?

**Comment by andy-twosticks** [comment]
Same.  Sorry, Coraline -- doesn't work for me. :(

**Comment by CoralineAda** [comment]
I'll see if I can fix this soon, so sorry!

**Comment by andy-twosticks** [comment]
I'm still getting this in Fuku 2.3.1...

**Comment by CoralineAda** [comment]
Sorry about that! Fixed in 2.3.2 (I hope!)
